language: go
go:
  - 1.12.x
git:
  # Needs to include the commit of the latest tag
  depth: 50
before_install:
  - mkdir -p $GOPATH/src/github.com/zylisp
script:
  - export GOPATH=${GOPATH}:${TRAVIS_BUILD_DIR}
  - export PATH=${PATH}:${TRAVIS_BUILD_DIR}/bin
  - make
notifications:
  email:
      - oubiwann@gmail.com
